### ISSUE TITLE
have problems with the code, 

### ISSUE THREAD

**Issue by Clarksh** [lushishuai/BERT-ROBERTA-pytorch-#1]
cannot understand the code in run_glue.py
`Array_logits=np.array((tem_logits.cpu()))`
               all_logits.append(Array_logits[0].tolist())`
                all_logits.append(Array_logits[1].tolist())
                all_logits.append(Array_logits[2].tolist())``

**Comment by lushishuai** [comment]
> cannot understand the code in run_glue.py
> `Array_logits=np.array((tem_logits.cpu()))`
> all_logits.append(Array_logits[0].tolist())`
> all_logits.append(Array_logits[1].tolist())
> all_logits.append(Array_logits[2].tolist())``

你好，访问您的主页，我看您是中国学生，我用中文回答一下哈。
这个主要是计算roc_auc值才做了这样的操作，在代码中，由于我最后的结果不需要roc_auc值，所以我把求roc_auc值的部分注释掉了。这一部分没有注释。
这个主要是把tensor类型转化为了narray，然后就可以append放在一起，便于后续操作计算roc_auc值。当然，tensor类型也可能有方式完成这样的计算，但是，我就想到了这种方法，所以就这么写了。
如果您对我的代码感兴趣，希望star一下，谢谢！
欢迎有问题继续交流

**Comment by Clarksh** [comment]
哦哦原来如此，感谢，我用你的代码跑通了模型。我现在在做一个两千分类的多标签分类，但是全部预测成了一种结果，正在排查问题。请问你最后预测的效果好吗？多亏你的答案，我看huggingface上面一直没有这个任务。

**Comment by lushishuai** [comment]
我做的是自动问答部分的实验，给出一句话，给这句话分配一些标签，bert的效果远高于普通的lstm模型

**Comment by lushishuai** [comment]
我那个是16个标签，没有你这么多，但是如果2000个标签中绝大部分标签不是长尾分布的话，我相信代码结果应该至少不会预测成一个结论。可以走一遍代码排查一下

**Comment by Clarksh** [comment]
你好，我把标签转换成3000维度的one-hot，但最终预测结果都成了一样的；减少为16个类别的话预测结果就会正常，所以怀疑是不是one-hot太过稀疏。

**Comment by Clarksh** [comment]
问题解决了，我让模型跑久一点就可以了，类别太多，学到后面才能学到

**Comment by Uingll** [comment]
您好，请问您在项目说明中提到的三个模型需要自己下载，可是我没有找到怎么去下载它们，请问您能不能给我发一下下载的地址或者已经下载的模型的，感激不尽！（1271013240@qq.com)

**Comment by Roxanne527** [comment]
您好，请问这个是什么原因呢
Traceback (most recent call last):
  File "/home/users/yuruoxuan/BERT-ROBERTA-pytorch-multi-label-classification/run_glue.py", line 663, in <module>
    main()
  File "/home/users/yuruoxuan/BERT-ROBERTA-pytorch-multi-label-classification/run_glue.py", line 613, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "/home/users/yuruoxuan/BERT-ROBERTA-pytorch-multi-label-classification/run_glue.py", line 178, in train
    outputs = model(**inputs)
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/users/yuruoxuan/BERT-ROBERTA-pytorch-multi-label-classification/modeling_bert1.py", line 977, in forward
    outputs = self.bert(input_ids,
  File "/home/users/yuruoxuan/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/users/yuruoxuan/BERT-ROBERTA-pytorch-multi-label-classification/modeling_bert1.py", line 612, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration
